const Games = [
  // {
  //   local: "NY Yankees",
  //   visit: "Red Sox",
  //   time: "5 FEB 9:00pm",
  //   league: "MLB",
  //   sport: "Baseball",
  //   image: "https://cdn1.iconfinder.com/data/icons/hawcons/32/700389-icon-2-baseball-512.png",
  //   traded: 7569,
  //   matches: 7,
  //   unmatched: 12,
  //   topBet: 590,
  //   pct: [],
  // },
  {
    local: {
      name: "Barcelona",
      quotes: [20, 35],
      position: 3
    },
    visit: {
      name: "Real Madrid",
      quotes: [-20, 22],
      position: 2
    },
    draw: {
      name: "Draw",
      quotes: [-35, -22],
      position: 1
    },
    time: "5 FEB 9:00pm",
    league: "La liga",
    sport: "Soccer",
    image: "https://icons-for-free.com/free-icons/png/512/315754.png",
    traded: 51600,
    matches: 15,
    unmatched: 20,
    topBet: 7000,
  },
  // {
  //   local: "Valencia",
  //   visit: "Sevilla",
  //   time: "5 FEB 9:00pm",
  //   league: "La liga",
  //   sport: "Soccer",
  //   image: "https://icons-for-free.com/free-icons/png/512/315754.png",
  //   traded: 2800,
  //   matches: 12,
  //   unmatched: 45,
  //   topBet: 121,
  // },
  // {
  //   local: "Patriots",
  //   visit: "Steelers",
  //   time: "5 FEB 9:00pm",
  //   league: "NFL",
  //   sport: "Football",
  //   image: "https://cdn2.iconfinder.com/data/icons/university-set-4/512/10-512.png",
  //   traded: 2450,
  //   matches: 55,
  //   unmatched: 12,
  //   topBet: 633,
  // },
  // {
  //   local: "Boca Juniors",
  //   visit: "River Plate",
  //   time: "5 FEB 9:00pm",
  //   league: "Copa Libertadores",
  //   sport: "Soccer",
  //   image: "https://icons-for-free.com/free-icons/png/512/315754.png",
  //   traded: 8573,
  //   matches: 157,
  //   unmatched: 123,
  //   topBet: 1233,
  // },
  // {
  //   local: "America",
  //   visit: "Chivas",
  //   time: "5 FEB 9:00pm",
  //   league: "Liga MX",
  //   sport: "Soccer",
  //   image: "https://icons-for-free.com/free-icons/png/512/315754.png",
  //   traded: 569,
  //   matches: 6,
  //   unmatched: 23,
  //   topBet: 233,
  // }
]

module.exports = Games;
