const Games = [
  {
    local: "NY Yankees",
    visit: "Red Sox",
    time: "5 FEB 9:00pm",
    league: "MLB",
    sport: "Baseball",
    image: "https://cdn1.iconfinder.com/data/icons/hawcons/32/700389-icon-2-baseball-512.png",
    traded: 1569,
    matches: 6,
    unmatched: 23,
  },
  {
    local: "Barcelona",
    visit: "Real Madrid",
    time: "5 FEB 9:00pm",
    league: "La liga",
    sport: "Soccer",
    image: "https://icons-for-free.com/free-icons/png/512/315754.png",
    traded: 1569,
    matches: 6,
    unmatched: 23,
  },
  {
    local: "Valencia",
    visit: "Sevilla",
    time: "5 FEB 9:00pm",
    league: "La liga",
    sport: "Soccer",
    image: "https://icons-for-free.com/free-icons/png/512/315754.png",
    traded: 1569,
    matches: 6,
    unmatched: 23,
  },
  {
    local: "Patriots",
    visit: "Steelers",
    time: "5 FEB 9:00pm",
    league: "NFL",
    sport: "Football",
    image: "https://cdn2.iconfinder.com/data/icons/university-set-4/512/10-512.png",
    traded: 1569,
    matches: 6,
    unmatched: 23,
  },
  {
    local: "Boca Juniors",
    visit: "River Plate",
    time: "5 FEB 9:00pm",
    league: "Copa Libertadores",
    sport: "Soccer",
    image: "https://icons-for-free.com/free-icons/png/512/315754.png",
    traded: 1569,
    matches: 6,
    unmatched: 23,
  },
  {
    local: "America",
    visit: "Chivas",
    time: "5 FEB 9:00pm",
    league: "Liga MX",
    sport: "Soccer",
    image: "https://icons-for-free.com/free-icons/png/512/315754.png",
    traded: 1569,
    matches: 6,
    unmatched: 23,
  }
]

module.exports = Games;
