# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Betmatcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Betmatcher
  pod 'Firebase/Analytics'

  # target 'Betmatcher-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'BetmatcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Betmatcher-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Betmatcher-tvOS

  target 'Betmatcher-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
